<?php
/*
Plugin Name: My Custom Post Type
Plugin URI: https://example.com/my-custom-post-type
Description: A custom post type plugin.
Version: 1.0.0
Author: Ali Joder
Author URI: https://example.com/
Text Domain: my-custom-post-type
Domain Path: /languages
*/

// Load the autoloader generated by Composer.
require_once plugin_dir_path(__FILE__) . 'vendor/autoload.php';

// Load the plugin instance.
\My_Custom_Post_Type\Custom_Post_Type::get_instance();
